export const DEFAULT_SETTINGS = {
  LIGHT_MEM_MODEL: 'claude-sonnet-4-6',
  LIGHT_MEM_CONTEXT_OBSERVATIONS: '50',
  LIGHT_MEM_WORKER_PORT: '37777',
  LIGHT_MEM_WORKER_HOST: '127.0.0.1',

  LIGHT_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  LIGHT_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  LIGHT_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  LIGHT_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  LIGHT_MEM_CONTEXT_FULL_COUNT: '0',
  LIGHT_MEM_CONTEXT_FULL_FIELD: 'narrative',
  LIGHT_MEM_CONTEXT_SESSION_COUNT: '10',

  LIGHT_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  LIGHT_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  LIGHT_MEM_EXCLUDED_PROJECTS: '',
  LIGHT_MEM_FOLDER_MD_EXCLUDE: '[]',
} as const;
